examples/usage.rs
src/comblog.rs
src/lib.rs
src/termlog.rs

I removed some `unwrap()` calls to avoid causing `panic` when not running the application in a terminal (for instance, a GUI application).

Remove unwrap

---

src/loggers/mod.rs

It failed with this error when using without the default features:
```
error[E0432]: unresolved import `self::termlog`
--> /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/simplelog-0.4.3/src/loggers/mod.rs:9:15
|
9 | pub use self::termlog::{TermLogger, TermLogError};
|               ^^^^^^^ Could not find `termlog` in `self`
error: aborting due to previous error
```

Fix compilation without default features

---

Cargo.toml
src/config.rs
src/lib.rs
src/loggers/logging.rs
src/loggers/termlog.rs

Add the time_format config option which will be used as the format string for writing the time.
I also replaced the `time` crate with `chrono` (https://github.com/chronotope/chrono) because it's more well supported.
https://github.com/Drakulix/simplelog.rs/issues/12

Configurable time format

---

Cargo.toml
examples/usage.rs
src/config.rs
src/lib.rs
src/loggers/comblog.rs
src/loggers/logging.rs
src/loggers/simplelog.rs
src/loggers/termlog.rs
src/loggers/writelog.rs

Initializing with a Box<Log> now uses the 'log::set_boxed_logger'
function which is feature gated behind the "std" feature.
Log implementations now define 'flush' method, which does nothing since
all loggers already flush in 'try_log'.
Records now can possibly fail to produce a file or line location, in
which case " &lt;unknown&gt;" will be displayed.

Update for log 0.4.1

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Updated to the latest versions of `log` and `term`, this was specifically because the latest version of `term` uses the `0.3+` version of winapi on Windows.
Also fixed a compiler warning about the unused macro import on `log` since the macros were only used in unit tests.

Dependency Upgrade

---

src/loggers/termlog.rs

Document why TermLogger::new could return None

---

src/config.rs
src/lib.rs
src/loggers/logging.rs
src/loggers/termlog.rs

Adds the ability to log the thread's name in place of the ID, also allows for a configurable padding setup.

Add logging for named threads and thread field padding

---

src/loggers/logging.rs

By using the `target()` method instead of `module_path()` we can extend the functionality of the `add_filter_allow` and `add_filter_ignore` to the case where the target is set manually and not defaulted to the module_path. This preserves the current functionality since if that `target` is not set, it defaults to the `module_path` as per the `log` crate spec:
> A log request consists of a target, a level, and a body. A target is a string which defaults to the module path of the location of the log request, though that default may be overridden. Logger implementations typically use the target to filter requests based on some user configuration.

Extended functionality for filter_allow and filter_ignore

---

src/loggers/termlog.rs

`TerminalMode` is just a plain enum, I see no reason for preventing it from having implementations of `Copy`, `Eq`, `Debug` and `Hash`. Without it, it is not possible to easily embed it in other types for which we wish to derive these traits as well (a case that I stumbled upon in my project).

Derive useful traits for the terminal mode type.

---

.travis.yml
Cargo.toml
examples/usage.rs
src/lib.rs
src/loggers/comblog.rs
src/loggers/mod.rs
src/loggers/termlog.rs

Change the dependency of `term` to `termcolor` now that `term` is no longer maintained as per https://github.com/Drakulix/simplelog.rs/issues/54.
It seems `termcolor` is slightly unreliable on macOS and sometimes doesn't colour the output, but I can't reliably reproduce it. It works fine on Windows and Ubuntu.
Also `termcolor` doesn't throw an error (at least during my tests) if it can't open stdout so I've removed the `Option` from `TermLogger::new()`
Fixes #54

Migrate to termcolor

---

README.md

The example from the README didn't work. While this is still different from usage.rs, it compiles.

Remove unwrap() on TermLogger::new() in README.

---

examples/custom_colors.rs
examples/default_colors.rs
examples/rgb_colors.rs
src/config.rs
src/lib.rs
src/loggers/termlog.rs

- Added `ConfigBuilder::set_level_color` to customize the colors of level labels for loggers that support color. 
- Added three examples showing the default colors, custom colors, and (if supported) RGB colors.
- Tested with and without the `termcolor` feature enabled.

Customizable level label colors

---

src/config.rs

Rename the arguments to `ConfigBuilder::add_filter_allow*` and `ConfigBuilder::add_filter_ignore*` from `time_format` to `filter_allow` and `filter_ignore`.  I assume the `time_format` thing was due to a bad copy-paste.
The use declarations at the top where also reordered by rustfmt.  I can undo that if you prefer.

Rename time_format to filter_allow/filter_ignore where appropriate

---

Cargo.toml
examples/custom_colors.rs
examples/default_colors.rs
examples/rgb_colors.rs
examples/usage.rs
src/config.rs
src/lib.rs
src/loggers/comblog.rs
src/loggers/termlog.rs

- **TermLogger: Expose termcolor::ColorChoice**
Command line interfaces that write colored output usually give users
an option to turn it off, or make it automatically shut off when writing
to a file, pipe, or unsupported terminal. termcolor already has some
nice machinery to handle this sort of thing with ColorChoice, so expose
it when creating a TermLogger.
Programmers (such as myself) who use simplelog and want to give users
this choice only have ugly alternatives. For example, you could fall
back to a WriteLogger if the user doesn't want color, but then you:
- Lose out on the "mixed" logging mode you get from TerminalMode::Mixed
- Have to reimplement nice ColorChoice::Auto behavior yourself,
on _top_ of termcolor.
- **TermLogger/ConfigBuilder: Make colors optional**
White isn't a good …

Expose termcolor's ColorChoice and make colors optional

---

README.md

Add `ColorChoice::Auto` to arguments for creating a `TermLogger`, as per v0.10 changes.

Update README.md to conform to v0.10

---

Cargo.toml
src/loggers/termlog.rs

Without it, termcolor issues _many, many_ small writes. This
increases performance by several orders of magnitude, at least on Linux.
Users should call `log::Log::flush()` to flush the log as-desired.

TermLogger: Use termcolor::BufferedStandardStream

---

Cargo.toml
src/loggers/termlog.rs

The log crate holds the logger as a `static mut` reference
which isn't dropped at program exit:
https://doc.rust-lang.org/reference/items/static-items.html
Sadly, this means we can't rely on the BufferedStandardStreams flushing
themselves on the way out, so to avoid the Case of the Missing 8k,
flush each entry.
Fixes #80

TermLogger: Flush each entry

---

Cargo.toml
src/config.rs
src/loggers/logging.rs
src/loggers/termlog.rs
src/paris_macros/mod.rs

This commit adds a possibility to color the log levels using an ansi_term
crate for this purpose.
The change was intended for WriteLogger in mind, but as this feature will
be configurable and put in generic logging code, then other loggers can
benefit as well (if desired).
This way one can easily create a logfile with a similar colored look
as it is printed real-time on a terminal/console.
Tip: To view such a logfile with colors using 'less' you can use:
less -R /path/to/logfile

introduce colored log levels using ansi_term

---

CHANGELOG.md
Cargo.toml
README.md

I forgot to bump crate version...

Bump version to v0.11.0 and adjust README

---

Cargo.toml

Hi
There was another parsing fix in paris crate. I think that using always the newest paris 1.5.x version will be better then always release new simplelog version after paris change...
This PR is doing this ....

Update paris crate and bump version

---

CHANGELOG.md
Cargo.toml
README.md
src/config.rs
src/lib.rs
src/loggers/logging.rs
src/loggers/testlog.rs

Replace chrono with time

---

examples/paris_demo/Cargo.toml
examples/paris_demo/src/main.rs
src/lib.rs
src/paris_macros/mod.rs

Please see: [Why should simplelog’s dependencies be introduced when its paris feature is enabled?](https://users.rust-lang.org/t/why-should-simplelogs-dependencies-be-introduced-when-its-paris-feature-is-enabled/72572)
Although [issue #91](https://github.com/Drakulix/simplelog.rs/issues/91) has been closed, this PR actually resolves it.

fix the problem of macro hygiene when paris is enabled

---

CHANGELOG.md

The changelogs were indented by 4 spaces making them code-blocks which are much harder to read if rendered. This replaces the 4 spaces with 1 space so the changelogs get rendered as text/list.

Make CHANGELOG.md more readable

---

src/loggers/testlog.rs

I noticed a `println!` where I would have expected a `print!` in the TestLogger's write_time function. This was causing log statements to be formatted as:
```
15:28:59
[INFO] [my_project/src/foo.rs:441] Finished Task 1
15:28:59
[INFO] [my_project/src/foo.rs:444] Processing 0 items for Task 2
15:29:01
[INFO] [my_project/src/bar.rs:482] 1 Total Result
```
With this change, TestLogger output looks like:
```
15:28:59 [INFO] [my_project/src/foo.rs:441] Finished Task 1
15:28:59 [INFO] [my_project/src/foo.rs:444] Processing 0 items for Task 2
15:29:01 [INFO] [my_project/src/bar.rs:482] 1 Total Result
```

Remove newline from TestLogger time output

---

CHANGELOG.md
src/loggers/comblog.rs
src/loggers/simplelog.rs
src/loggers/termlog.rs
src/loggers/testlog.rs
src/loggers/writelog.rs

The `new` method of loggers are now `#[must_use]` to prevent confusion when `new` is used called instead of `init`.  
Currently the following code will appear completely valid but silently not do any logging:
```rust
use log::*;
use simplelog::*;
fn main() {
TermLogger::new(
LevelFilter::Trace,
Config::default(),
TerminalMode::Stdout,
ColorChoice::Auto,
);
error!("Red error");
warn!("Yellow warning");
info!("Blue info");
debug!("Cyan debug");
trace!("White trace");
}
```
With this change a compiler warning is generated on `new`.

The `new` method of loggers are now `#[must_use]`

---

src/config.rs
src/loggers/logging.rs
src/loggers/termlog.rs
src/loggers/testlog.rs

Add posibility to print module

---

src/config.rs

This just changes a doc comment to use backticks to wrap an format string rather than double quotes. Elsewhere in the crate format strings are wrapped in bacckticks in doc comments, so this seemed like the most consistent solution.
---
I noticed these coming up in PR diffs and figured it was an easy fix.

Fix warnings in `cargo doc` from invalid link

---

src/config.rs

This makes the builder easier to access, without needing to import ConfigBuilder

Add builder() associated function to Config to make a ConfigBuilder

---

Cargo.toml
src/config.rs
src/loggers/logging.rs
src/loggers/termlog.rs

Added a config option for different line endings. '\n' is quite ubiquitous but not used everywhere (Old versions of DOS/Windows). For the niche use cases were someone wants their log files to have a different line ending this could be helpful.

Add config option for line endings.
